# Generated by Django 4.2 on 2023-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=1000, verbose_name='balance'),
        ),
    ]
