# Generated by Django 4.2 on 2023-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_balance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='history_of_balance',
            field=models.TextField(default=models.IntegerField(default=1000, verbose_name='balance'), verbose_name='history'),
        ),
    ]
