# Generated by Django 4.2 on 2023-04-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_payment_history_of_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='history_of_balance',
            field=models.TextField(default=1000, verbose_name='history'),
        ),
    ]
