# Generated by Django 4.2 on 2023-04-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payment_history_of_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='history_of_balance',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='users.payment', verbose_name='history'),
        ),
    ]
