# Generated by Django 4.2 on 2023-04-21 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payment_history_of_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='history_of_balance',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
    ]
