# Generated by Django 4.2 on 2023-04-21 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_payment_history_of_balance_historicalpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_balance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
