# Generated by Django 4.2 on 2023-04-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_payment_user_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPayment',
        ),
    ]
